[pytest]
addopts = --cov=mywhisper --cov-report=term-missing --cov-fail-under=80
testpaths = tests
filterwarnings =
    ignore::UserWarning:pyannote.audio.core.io
    ignore:torchaudio._backend.utils.info has been deprecated:UserWarning

